version: "3"

services:
  landing-page:
    image: "santoshbitradocker/devops-landing-page:latest" # You could pin the version (e.g., Landing-page:9.9)
    ports:
      - "8082:8082"
    restart: unless-stopped  # Ensures Landing-Page container restarts on failure
