version: "3"

services:
  landing-page:
    image: "santoshbitradocker/devops-landing-page:latest" # You could pin the version (e.g., Landing-page:9.9)
    volumes:
      - landing-page-data:/mnt/data/landing-page-data/data
    ports:
      - "8082:80"
    restart: unless-stopped  # Ensures Landing-Page container restarts on failure

volumes:
  landing-page-data: 